In [6]:
import pandas as pd
df_fact = pd.read_csv("FACT_SALES.csv")
df_fact

,WEEK,ITEM_CODE,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES,REGION
0,34-22,7501058792808BP2,0.006,0.139,1.000,TOTAL AUTOS AREA 5
1,34-22,7501058715883,0.487,116.519,2.916,TOTAL AUTOS AREA 5
2,34-22,7702626213774,1.391,68.453,5.171,TOTAL AUTOS AREA 5
3,34-22,7501058716422,0.022,1.481,1.833,TOTAL AUTOS AREA 5
4,34-22,7501058784353,2.037,182.839,5.375,TOTAL AUTOS AREA 5
...,...,...,...,...,...,...
121997,26-23,7501058792778BP1,1.192,150.829,4.000,TOTAL AUTOS SCANNING MEXICO
121998,26-23,7501058757630,1.947,235.416,2.797,TOTAL AUTOS SCANNING MEXICO
121999,26-23,7501058753441,18.013,429.289,9.102,TOTAL AUTOS SCANNING MEXICO
122000,26-23,7702626204208BP1,21.152,210.276,22.172,TOTAL AUTOS SCANNING MEXICO
122001,26-23,7501058784346,1.468,301.973,2.068,TOTAL AUTOS SCANNING MEXICO

In [7]:
import pandas as pd
df_cal = pd.read_excel("DIM_CALENDAR.xlsx")
df_cal

      WEEK  YEAR  MONTH  WEEK_NUMBER       DATE
0    01-21  2021      1            1 2021-01-10
1    02-21  2021      1            2 2021-01-17
2    03-21  2021      1            3 2021-01-24
3    04-21  2021      1            4 2021-01-31
4    05-21  2021      2            5 2021-02-07
..     ...   ...    ...          ...        ...
151  48-23  2023     12           48 2023-12-04
152  49-23  2023     12           49 2023-12-11
153  50-23  2023     12           50 2023-12-18
154  51-23  2023     12           51 2023-12-25
155  52-23  2023      1           52 2024-01-01

[156 rows x 5 columns]

In [8]:
df_categ = pd.read_csv("DIM_CATEGORY.csv")
df_categ

   ID_CATEGORY                        CATEGORY
0            1  FABRIC TREATMENT and SANIT\r\n
1            2                       AIR CARE
2            3                    LAVAVAJILLAS
3            4                MEGA SUPERFICIES
4            5             LAVATORY CARE & BRC

In [9]:
df_prod = pd.read_excel("DIM_PRODUCT.xlsx")
df_prod

,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY,FORMAT,ATTR1,ATTR2,ATTR3
0,INDS. ALEN,CLORALEX,0000075000592,CLORALEX EL RENDIDOR BOT.PLAST. 250ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
1,INDS. ALEN,CLORALEX,0000075000608,CLORALEX EL RENDIDOR BOT.PLAST. 500ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
2,INDS. ALEN,CLORALEX,0000075000615,CLORALEX EL RENDIDOR BOT.PLAST. 950ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
3,INDS. ALEN,CLORALEX,0000075000622,CLORALEX EL RENDIDOR BOT.PLAST. 2000ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
4,INDS. ALEN,CLORALEX,0000075000639,CLORALEX EL RENDIDOR BOT.PLAST. 3750ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
...,...,...,...,...,...,...,...,...,...
500,RECKITT,VANISH,7501058789778BP1,VANISH EXT HIGIENE REM MANCHAS GAL 4LT + VANIS...,1,LIQUIDO,SAFE BLEACH,FABRIC TREATMENT,ROSA
501,INDS. ALEN,CLORALEX,7501025412142,CLORALEX AROMAS BLANQUEADOR C/AROMA LAVANDA GA...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
502,INDS. ALEN,CLORALEX,NaN,CLORALEX EL RENDIDOR BOT PLAST 2LT,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
503,CLOROX,CLOROX,NaN,CLOROX MASCOTAS BLANQUEADOR+DETERGENTE GALON 10L,1,LIQUIDO,CLORO,CLORO,MASCOTAS
504,CLOROX,CLOROX,7502240948188BP1,CLOROX BLANQ930M+MMBLANQINOD709M+MMFIBRAULTRA1...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO

In [10]:
df_segm = pd.read_excel("DIM_PRODUCT.xlsx")
df_segm

,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY,FORMAT,ATTR1,ATTR2,ATTR3
0,INDS. ALEN,CLORALEX,0000075000592,CLORALEX EL RENDIDOR BOT.PLAST. 250ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
1,INDS. ALEN,CLORALEX,0000075000608,CLORALEX EL RENDIDOR BOT.PLAST. 500ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
2,INDS. ALEN,CLORALEX,0000075000615,CLORALEX EL RENDIDOR BOT.PLAST. 950ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
3,INDS. ALEN,CLORALEX,0000075000622,CLORALEX EL RENDIDOR BOT.PLAST. 2000ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
4,INDS. ALEN,CLORALEX,0000075000639,CLORALEX EL RENDIDOR BOT.PLAST. 3750ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
...,...,...,...,...,...,...,...,...,...
500,RECKITT,VANISH,7501058789778BP1,VANISH EXT HIGIENE REM MANCHAS GAL 4LT + VANIS...,1,LIQUIDO,SAFE BLEACH,FABRIC TREATMENT,ROSA
501,INDS. ALEN,CLORALEX,7501025412142,CLORALEX AROMAS BLANQUEADOR C/AROMA LAVANDA GA...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
502,INDS. ALEN,CLORALEX,NaN,CLORALEX EL RENDIDOR BOT PLAST 2LT,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
503,CLOROX,CLOROX,NaN,CLOROX MASCOTAS BLANQUEADOR+DETERGENTE GALON 10L,1,LIQUIDO,CLORO,CLORO,MASCOTAS
504,CLOROX,CLOROX,7502240948188BP1,CLOROX BLANQ930M+MMBLANQINOD709M+MMFIBRAULTRA1...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO

In [11]:
print(df_fact.head())

    WEEK         ITEM_CODE  TOTAL_UNIT_SALES  TOTAL_VALUE_SALES  \
0  34-22  7501058792808BP2             0.006              0.139
1  34-22     7501058715883             0.487            116.519
2  34-22     7702626213774             1.391             68.453
3  34-22     7501058716422             0.022              1.481
4  34-22     7501058784353             2.037            182.839

   TOTAL_UNIT_AVG_WEEKLY_SALES              REGION
0                        1.000  TOTAL AUTOS AREA 5
1                        2.916  TOTAL AUTOS AREA 5
2                        5.171  TOTAL AUTOS AREA 5
3                        1.833  TOTAL AUTOS AREA 5
4                        5.375  TOTAL AUTOS AREA 5

In [12]:
print(df_cal.head())

    WEEK  YEAR  MONTH  WEEK_NUMBER       DATE
0  01-21  2021      1            1 2021-01-10
1  02-21  2021      1            2 2021-01-17
2  03-21  2021      1            3 2021-01-24
3  04-21  2021      1            4 2021-01-31
4  05-21  2021      2            5 2021-02-07

In [12]:
print(df_categ.head())

   ID_CATEGORY                        CATEGORY
0            1  FABRIC TREATMENT and SANIT\r\n
1            2                       AIR CARE
2            3                    LAVAVAJILLAS
3            4                MEGA SUPERFICIES
4            5             LAVATORY CARE & BRC

In [13]:
print(df_prod.head())

  MANUFACTURER     BRAND           ITEM  \
0   INDS. ALEN  CLORALEX  0000075000592
1   INDS. ALEN  CLORALEX  0000075000608
2   INDS. ALEN  CLORALEX  0000075000615
3   INDS. ALEN  CLORALEX  0000075000622
4   INDS. ALEN  CLORALEX  0000075000639

                                    ITEM_DESCRIPTION  CATEGORY   FORMAT  \
0  CLORALEX EL RENDIDOR BOT.PLAST. 250ML NAL. 000...         1  LIQUIDO
1  CLORALEX EL RENDIDOR BOT.PLAST. 500ML NAL. 000...         1  LIQUIDO
2  CLORALEX EL RENDIDOR BOT.PLAST. 950ML NAL. 000...         1  LIQUIDO
3  CLORALEX EL RENDIDOR BOT.PLAST. 2000ML NAL 000...         1  LIQUIDO
4  CLORALEX EL RENDIDOR BOT.PLAST. 3750ML NAL 000...         1  LIQUIDO

   ATTR1  ATTR2        ATTR3
0  CLORO  CLORO  NO DEFINIDO
1  CLORO  CLORO  NO DEFINIDO
2  CLORO  CLORO  NO DEFINIDO
3  CLORO  CLORO  NO DEFINIDO
4  CLORO  CLORO  NO DEFINIDO

In [14]:
print(df_segm.head())

  MANUFACTURER     BRAND           ITEM  \
0   INDS. ALEN  CLORALEX  0000075000592
1   INDS. ALEN  CLORALEX  0000075000608
2   INDS. ALEN  CLORALEX  0000075000615
3   INDS. ALEN  CLORALEX  0000075000622
4   INDS. ALEN  CLORALEX  0000075000639

                                    ITEM_DESCRIPTION  CATEGORY   FORMAT  \
0  CLORALEX EL RENDIDOR BOT.PLAST. 250ML NAL. 000...         1  LIQUIDO
1  CLORALEX EL RENDIDOR BOT.PLAST. 500ML NAL. 000...         1  LIQUIDO
2  CLORALEX EL RENDIDOR BOT.PLAST. 950ML NAL. 000...         1  LIQUIDO
3  CLORALEX EL RENDIDOR BOT.PLAST. 2000ML NAL 000...         1  LIQUIDO
4  CLORALEX EL RENDIDOR BOT.PLAST. 3750ML NAL 000...         1  LIQUIDO

   ATTR1  ATTR2        ATTR3
0  CLORO  CLORO  NO DEFINIDO
1  CLORO  CLORO  NO DEFINIDO
2  CLORO  CLORO  NO DEFINIDO
3  CLORO  CLORO  NO DEFINIDO
4  CLORO  CLORO  NO DEFINIDO

In [16]:
print(df_fact.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122002 entries, 0 to 122001
Data columns (total 6 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   WEEK                         122002 non-null  object
 1   ITEM_CODE                    122002 non-null  object
 2   TOTAL_UNIT_SALES             122002 non-null  float64
 3   TOTAL_VALUE_SALES            122002 non-null  float64
 4   TOTAL_UNIT_AVG_WEEKLY_SALES  122002 non-null  float64
 5   REGION                       122002 non-null  object
dtypes: float64(3), object(3)
memory usage: 5.6+ MB
None

In [17]:
print(df_cal.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   WEEK         156 non-null    object
 1   YEAR         156 non-null    int64
 2   MONTH        156 non-null    int64
 3   WEEK_NUMBER  156 non-null    int64
 4   DATE         156 non-null    datetime64[ns]
dtypes: datetime64[ns](1), int64(3), object(1)
memory usage: 6.2+ KB
None

In [18]:
print(df_categ.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID_CATEGORY  5 non-null      int64
 1   CATEGORY     5 non-null      object
dtypes: int64(1), object(1)
memory usage: 212.0+ bytes
None

In [19]:
print(df_prod.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505 entries, 0 to 504
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   MANUFACTURER      505 non-null    object
 1   BRAND             505 non-null    object
 2   ITEM              503 non-null    object
 3   ITEM_DESCRIPTION  505 non-null    object
 4   CATEGORY          505 non-null    int64
 5   FORMAT            505 non-null    object
 6   ATTR1             499 non-null    object
 7   ATTR2             505 non-null    object
 8   ATTR3             499 non-null    object
dtypes: int64(1), object(8)
memory usage: 35.6+ KB
None

In [20]:
print(df_segm.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505 entries, 0 to 504
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   MANUFACTURER      505 non-null    object
 1   BRAND             505 non-null    object
 2   ITEM              503 non-null    object
 3   ITEM_DESCRIPTION  505 non-null    object
 4   CATEGORY          505 non-null    int64
 5   FORMAT            505 non-null    object
 6   ATTR1             499 non-null    object
 7   ATTR2             505 non-null    object
 8   ATTR3             499 non-null    object
dtypes: int64(1), object(8)
memory usage: 35.6+ KB
None

In [21]:
print(df_fact.describe())

       TOTAL_UNIT_SALES  TOTAL_VALUE_SALES  TOTAL_UNIT_AVG_WEEKLY_SALES
count     122002.000000      122002.000000                122002.000000
mean           3.211097          90.513761                    10.099904
std           14.496009         350.236505                    22.650142
min            0.000000           0.001000                     0.042000
25%            0.063000           2.662000                     2.316000
50%            0.367000          16.812000                     3.993500
75%            1.520000          62.961500                     8.898000
max          504.681000       12236.759000                   794.000000

In [22]:
print(df_cal.describe())

              YEAR       MONTH  WEEK_NUMBER                 DATE
count   156.000000  156.000000   156.000000                  156
mean   2022.000000    6.487179    26.500000  2022-07-06 20:00:00
min    2021.000000    1.000000     1.000000  2021-01-10 00:00:00
25%    2021.000000    3.750000    13.750000  2021-10-08 06:00:00
50%    2022.000000    6.500000    26.500000  2022-07-06 12:00:00
75%    2023.000000    9.250000    39.250000  2023-04-04 18:00:00
max    2023.000000   12.000000    52.000000  2024-01-01 00:00:00
std       0.819126    3.459419    15.056667                  NaN

In [23]:
print(df_categ.describe())

       ID_CATEGORY
count     5.000000
mean      3.000000
std       1.581139
min       1.000000
25%       2.000000
50%       3.000000
75%       4.000000
max       5.000000

In [24]:
print(df_prod.describe())

       CATEGORY
count     505.0
mean        1.0
std         0.0
min         1.0
25%         1.0
50%         1.0
75%         1.0
max         1.0

In [26]:
print(df_segm.describe())

       CATEGORY
count     505.0
mean        1.0
std         0.0
min         1.0
25%         1.0
50%         1.0
75%         1.0
max         1.0

In [27]:
df_fact.isnull().sum()

WEEK                           0
ITEM_CODE                      0
TOTAL_UNIT_SALES               0
TOTAL_VALUE_SALES              0
TOTAL_UNIT_AVG_WEEKLY_SALES    0
REGION                         0
dtype: int64

In [28]:
df_cal.isnull().sum()

WEEK           0
YEAR           0
MONTH          0
WEEK_NUMBER    0
DATE           0
dtype: int64

In [29]:
df_categ.isnull().sum()

ID_CATEGORY    0
CATEGORY       0
dtype: int64

In [30]:
df_prod.isnull().sum()

MANUFACTURER        0
BRAND               0
ITEM                2
ITEM_DESCRIPTION    0
CATEGORY            0
FORMAT              0
ATTR1               6
ATTR2               0
ATTR3               6
dtype: int64

In [31]:
df_segm.isnull().sum()

MANUFACTURER        0
BRAND               0
ITEM                2
ITEM_DESCRIPTION    0
CATEGORY            0
FORMAT              0
ATTR1               6
ATTR2               0
ATTR3               6
dtype: int64

In [36]:
df_prod2 = df_prod.dropna()

In [37]:
df_prod2.isnull().sum()

MANUFACTURER        0
BRAND               0
ITEM                0
ITEM_DESCRIPTION    0
CATEGORY            0
FORMAT              0
ATTR1               0
ATTR2               0
ATTR3               0
dtype: int64

In [38]:
df_segm2 = df_segm.dropna()

In [39]:
df_segm2.isnull().sum()

MANUFACTURER        0
BRAND               0
ITEM                0
ITEM_DESCRIPTION    0
CATEGORY            0
FORMAT              0
ATTR1               0
ATTR2               0
ATTR3               0
dtype: int64

In [41]:
df_prod.shape

(505, 9)

In [44]:
df_prod_sindup = df_prod.drop_duplicates("ITEM")

In [45]:
df_prod_sindup.shape

(504, 9)

In [13]:
pd.merge(df_fact, df_prod, left_on = "ITEM_CODE", right_on = "ITEM")

,WEEK,ITEM_CODE,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES,REGION,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY,FORMAT,ATTR1,ATTR2,ATTR3
0,34-22,7501058792808BP2,0.006,0.139,1.000,TOTAL AUTOS AREA 5,RECKITT,VANISH,7501058792808BP2,VANISHOXIACTIONROSADOYPACK120GR+MMCRYSTALWHITE...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA
1,06-22,7501058792808BP2,0.023,0.529,1.917,TOTAL AUTOS AREA 2,RECKITT,VANISH,7501058792808BP2,VANISHOXIACTIONROSADOYPACK120GR+MMCRYSTALWHITE...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA
2,47-22,7501058792808BP2,0.004,0.036,1.333,TOTAL AUTOS AREA 5,RECKITT,VANISH,7501058792808BP2,VANISHOXIACTIONROSADOYPACK120GR+MMCRYSTALWHITE...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA
3,13-22,7501058792808BP2,0.059,1.361,1.967,TOTAL AUTOS AREA 5,RECKITT,VANISH,7501058792808BP2,VANISHOXIACTIONROSADOYPACK120GR+MMCRYSTALWHITE...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA
4,35-22,7501058792808BP2,0.029,0.662,2.071,TOTAL AUTOS SCANNING MEXICO,RECKITT,VANISH,7501058792808BP2,VANISHOXIACTIONROSADOYPACK120GR+MMCRYSTALWHITE...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121997,26-23,7501071900242,0.001,0.037,1.000,TOTAL AUTOS SCANNING MEXICO,CLOROX,CLOROX,7501071900242,CLOROX FLORAL BOTELLA 3800 ML. 7501071900242,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
121998,24-23,7501025412418,0.001,0.044,1.000,TOTAL AUTOS AREA 2,INDS. ALEN,CLORALEX,7501025412418,CLORALEX COLOR PODER VINAGRE BOT 1800 ML NAL 7...,1,LIQUIDO,SAFE BLEACH,FABRIC TREATMENT,PRE LAVADOR
121999,24-23,7501025412418,0.001,0.044,1.000,TOTAL AUTOS SCANNING MEXICO,INDS. ALEN,CLORALEX,7501025412418,CLORALEX COLOR PODER VINAGRE BOT 1800 ML NAL 7...,1,LIQUIDO,SAFE BLEACH,FABRIC TREATMENT,PRE LAVADOR
122000,25-23,7501058716446,0.001,0.007,1.000,TOTAL AUTOS AREA 6,RECKITT,VANISH,7501058716446,VANISH OXI ACTION CRISTAL WHITE AHORRO DEL 25%...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,BLANCO
122001,25-23,7501058716446,0.001,0.007,1.000,TOTAL AUTOS SCANNING MEXICO,RECKITT,VANISH,7501058716446,VANISH OXI ACTION CRISTAL WHITE AHORRO DEL 25%...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,BLANCO

In [15]:
pd.merge(df_segm, df_categ, left_on = "CATEGORY", right_on = "ID_CATEGORY")

,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY_x,FORMAT,ATTR1,ATTR2,ATTR3,ID_CATEGORY,CATEGORY_y
0,INDS. ALEN,CLORALEX,0000075000592,CLORALEX EL RENDIDOR BOT.PLAST. 250ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,1,FABRIC TREATMENT and SANIT\r\n
1,INDS. ALEN,CLORALEX,0000075000608,CLORALEX EL RENDIDOR BOT.PLAST. 500ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,1,FABRIC TREATMENT and SANIT\r\n
2,INDS. ALEN,CLORALEX,0000075000615,CLORALEX EL RENDIDOR BOT.PLAST. 950ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,1,FABRIC TREATMENT and SANIT\r\n
3,INDS. ALEN,CLORALEX,0000075000622,CLORALEX EL RENDIDOR BOT.PLAST. 2000ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,1,FABRIC TREATMENT and SANIT\r\n
4,INDS. ALEN,CLORALEX,0000075000639,CLORALEX EL RENDIDOR BOT.PLAST. 3750ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,1,FABRIC TREATMENT and SANIT\r\n
...,...,...,...,...,...,...,...,...,...,...,...
500,RECKITT,VANISH,7501058789778BP1,VANISH EXT HIGIENE REM MANCHAS GAL 4LT + VANIS...,1,LIQUIDO,SAFE BLEACH,FABRIC TREATMENT,ROSA,1,FABRIC TREATMENT and SANIT\r\n
501,INDS. ALEN,CLORALEX,7501025412142,CLORALEX AROMAS BLANQUEADOR C/AROMA LAVANDA GA...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,1,FABRIC TREATMENT and SANIT\r\n
502,INDS. ALEN,CLORALEX,NaN,CLORALEX EL RENDIDOR BOT PLAST 2LT,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,1,FABRIC TREATMENT and SANIT\r\n
503,CLOROX,CLOROX,NaN,CLOROX MASCOTAS BLANQUEADOR+DETERGENTE GALON 10L,1,LIQUIDO,CLORO,CLORO,MASCOTAS,1,FABRIC TREATMENT and SANIT\r\n
504,CLOROX,CLOROX,7502240948188BP1,CLOROX BLANQ930M+MMBLANQINOD709M+MMFIBRAULTRA1...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,1,FABRIC TREATMENT and SANIT\r\n